import assert from 'node:assert/strict';
import {test} from 'node:test';
import {BetaUsageLimiter} from '../src/worker.js';

const principal='a'.repeat(64);
const config={STRIPE_BILLING_MODE:'test',STRIPE_PRICE_ID:'price_fixture'};
const grant={eventId:'evt_first',invoiceId:'in_first',customerId:'cus_fixture',subscriptionId:'sub_fixture',priceId:'price_fixture',livemode:false,periodStart:1800000000000,periodEnd:1802678400000};
function setup(configuration=config) {
 const values=new Map([[`paid-binding:cus_fixture`,{principal,subscriptionId:'sub_fixture'}]]);let queue=Promise.resolve();
 const storage={get:async k=>structuredClone(values.get(k)),put:async(k,v)=>{if(typeof k==='object')for(const [key,value]of Object.entries(k))values.set(key,structuredClone(value));else values.set(k,structuredClone(v));},transaction(cb){const run=queue.then(async()=>{const snapshot=structuredClone(values);try{return await cb(storage);}catch(e){values.clear();for(const [k,v]of snapshot)values.set(k,v);throw e;}});queue=run.catch(()=>{});return run;}};
 const limiter=new BetaUsageLimiter({storage},configuration);
 const call=async(path,body)=>{const response=await limiter.fetch(new Request(`https://usage.internal${path}`,{method:'POST',body:JSON.stringify(body)}));return {status:response.status,...await response.json()};};
 const reserve=(extra={})=>call('/reserve',{day:'2027-01-15',timestamp:1800000001000,inviteHash:`paid:${principal}`,inviteLimit:3,inviteWindowMs:604800000,budgetMicroUsd:100,requestCostMicroUsd:1,...extra});
 return {values,storage,call,reserve};
}
test('paid invoice is durable and replay never refills consumption',async()=>{const s=setup();assert.equal((await s.call('/billing/grant',grant)).granted,true);assert.equal((await s.reserve()).allowed,true);for(const patch of [{},{eventId:'evt_second'},{eventId:'evt_third',invoiceId:'in_other'}])await s.call('/billing/grant',{...grant,...patch});assert.equal(s.values.get(`paid-credit:${principal}`).remaining,9);});
test('concurrent last-credit reservations share the global transaction',async()=>{const s=setup();await s.call('/billing/grant',grant);const results=await Promise.all(Array.from({length:15},()=>s.reserve()));assert.equal(results.filter(x=>x.allowed).length,10);assert.equal(s.values.get('2027-01-15:budget'),10);});
test('provider budget rejection leaves paid credits untouched',async()=>{const s=setup();await s.call('/billing/grant',grant);assert.equal((await s.reserve({budgetMicroUsd:1,requestCostMicroUsd:2})).reason,'daily_budget');assert.equal(s.values.get(`paid-credit:${principal}`).remaining,10);});
test('new paid period resets to ten; stale and overlapping periods cannot roll it back',async()=>{const s=setup();await s.call('/billing/grant',grant);await s.reserve();const next={...grant,eventId:'evt_new',invoiceId:'in_new',periodStart:grant.periodEnd,periodEnd:1805097600000};assert.equal((await s.call('/billing/grant',next)).granted,true);assert.equal(s.values.get(`paid-credit:${principal}`).remaining,10);for(const g of [grant,{...grant,eventId:'evt_overlap',invoiceId:'in_overlap',periodStart:grant.periodStart+1,periodEnd:next.periodEnd+1}])assert.notEqual((await s.call('/billing/grant',g)).granted,true);assert.equal(s.values.get(`paid-credit:${principal}`).periodStart,next.periodStart);});
for(const [name,patch] of [['live',{livemode:true}],['price',{priceId:'price_wrong'}],['unbound customer',{customerId:'cus_unknown'}],['other subscription',{subscriptionId:'sub_other'}],['invalid period',{periodEnd:0}],['forged principal',{principal:'b'.repeat(64)}]])test(`grant fails closed: ${name}`,async()=>{const s=setup();assert.equal((await s.call('/billing/grant',{...grant,...patch})).status,400);assert.equal(s.values.has(`paid-credit:${principal}`),false);});
for(const config of [{},{STRIPE_BILLING_MODE:'live',STRIPE_PRICE_ID:'price_fixture'},{STRIPE_BILLING_MODE:'test'}])test(`missing/test-only config ${JSON.stringify(config)}`,async()=>{const s=setup(config);assert.equal((await s.call('/billing/grant',grant)).status,503);assert.equal((await s.reserve()).allowed,false);});
test('expired paid identity never falls back to invite or unlimited usage',async()=>{const s=setup();await s.call('/billing/grant',grant);assert.equal((await s.reserve({timestamp:grant.periodEnd,unlimited:true})).allowed,false);assert.equal(s.values.has('2027-01-15:budget'),false);});
test('lifecycle block is monotonic and replays cannot re-enable subscription',async()=>{const s=setup();await s.call('/billing/grant',grant);assert.equal((await s.call('/billing/block',{customerId:grant.customerId,subscriptionId:grant.subscriptionId})).blocked,true);assert.equal((await s.reserve()).allowed,false);assert.notEqual((await s.call('/billing/grant',{...grant,eventId:'evt_late',invoiceId:'in_late',periodStart:grant.periodEnd,periodEnd:1805097600000})).granted,true);});
test('storage failure rolls back both provider budget and credit debit',async()=>{const s=setup();await s.call('/billing/grant',grant);const put=s.storage.put;s.storage.put=async(...args)=>{await put(...args);throw Error('synthetic storage failure');};await assert.rejects(s.reserve());assert.equal(s.values.get(`paid-credit:${principal}`).remaining,10);assert.equal(s.values.has('2027-01-15:budget'),false);});
