import {test} from 'node:test';
import assert from 'node:assert/strict';
import {BetaUsageLimiter,createHandler} from '../src/worker.js';
test('unconfigured email adapter fails closed before durable creation',async()=>{const s=setup();const h=createHandler();const r=await h(new Request('https://api.example/v1/subscriber/challenge',{method:'POST',headers:{Origin:'https://app.example','Content-Type':'application/json'},body:JSON.stringify({email:'payer@example.com',browserToken:s.browserToken})}),s.env);assert.equal(r.status,503);assert.equal(s.values.size,0);});
test('GET is non-consuming; body bounds and preflight are enforced',async()=>{const s=setup();await s.start();const token=s.token();const request=method=>new Request('https://api.example/v1/subscriber/verify',{method,headers:{Origin:'https://app.example'}});assert.equal((await s.handler(request('GET'),s.env)).status,405);const preflight=await s.handler(request('OPTIONS'),s.env);assert.equal(preflight.status,204);assert.match(preflight.headers.get('Access-Control-Allow-Headers'),/Authorization/);assert.equal((await s.call('challenge',{email:'x'.repeat(3000)})).status,400);assert.equal((await s.call('verify',{token,browserToken:s.browserToken})).status,200);});
test('network and global email ceilings bound storage and delivery',async()=>{const s=setup();for(let i=0;i<12;i++)await s.call('challenge',{email:`payer${i}@example.com`,browserToken:s.browserToken});assert.equal(s.mail.length,10);for(let i=0;i<110;i++)await s.call('challenge',{email:`other${i}@example.com`,browserToken:s.browserToken},{'CF-Connecting-IP':`192.0.2.${i}`});assert.equal(s.mail.length,100);});
test('storage failure returns sanitized retriable failure',async()=>{const s=setup();s.storage.transaction=async()=>{throw Error('private email provider token');};const r=await s.start();assert.equal(r.status,503);assert.equal((await r.text()).includes('private'),false);});
test('failed delivery remains unredeemable even when discard storage fails; quotas are not refunded',async()=>{
 const s=setup();let token,calls=0;const handler=createHandler({now:()=>1800000000000,subscriberEmailSender:async m=>{calls++;token=new URL(m.url).hash.slice(1).split('=').at(-1);return false;}});
 const original=s.env.BETA_USAGE_LIMITER.get;s.env.BETA_USAGE_LIMITER.get=()=>({fetch:(u,o)=>String(u).endsWith('/discard')?Promise.reject(Error('private provider error')):original().fetch(u,o)});
 for(let i=0;i<5;i++) {const r=await handler(new Request('https://api.example/v1/subscriber/challenge',{method:'POST',headers:{Origin:'https://app.example','Content-Type':'application/json'},body:JSON.stringify({email:'payer@example.com',browserToken:s.browserToken})}),s.env);assert.ok([202,503].includes(r.status));assert.ok(!(await r.text()).includes('private'));}
 assert.equal(calls,3);assert.equal((await s.call('verify',{token,browserToken:s.browserToken})).status,401);assert.equal([...s.values.keys()].some(k=>k.startsWith('subscriber:session:')),false);
});
test('default Resend adapter mounts only when configured; rejects delivery without usable challenge or leaked logs',async()=>{
 const s=setup();Object.assign(s.env,{SUBSCRIBER_EMAIL_PROVIDER:'resend',RESEND_API_KEY:'re_synthetic_only',SUBSCRIBER_EMAIL_FROM:'signin@auth.example.com',SUBSCRIBER_EMAIL_TRACKING_DISABLED:'true'});
 const original=globalThis.fetch,originalLog=console.log,originalError=console.error;let captured,calls=0;const logs=[];
 const handler=createHandler({now:()=>1800000000000});
 const start=()=>handler(new Request('https://api.example/v1/subscriber/challenge',{method:'POST',headers:{Origin:'https://app.example','Content-Type':'application/json'},body:JSON.stringify({email:'payer@example.com',browserToken:s.browserToken})}),s.env);
 try {
 console.log=console.error=(...args)=>logs.push(args);
 globalThis.fetch=async(u,o)=>{calls++;assert.equal(u,'https://api.resend.com/emails');captured=JSON.parse(o.body).text.match(/#subscriber_verify=([a-f0-9]{64})/)[1];return new Response('private '+captured+' payer@example.com',{status:429});};
 assert.deepEqual(await (await start()).json(),{accepted:true});assert.equal((await s.call('verify',{token:captured,browserToken:s.browserToken})).status,401);assert.equal([...s.values.keys()].some(k=>k.startsWith('subscriber:challenge:')),false);
 globalThis.fetch=async(u,o)=>{calls++;captured=JSON.parse(o.body).text.match(/#subscriber_verify=([a-f0-9]{64})/)[1];return Response.json({id:'49a3999c-0ce1-4ea6-ab68-afcd6dc2e794'});};
 assert.equal((await start()).status,202);assert.equal((await s.call('verify',{token:captured,browserToken:s.browserToken})).status,200);assert.equal(calls,2);assert.deepEqual(logs,[]);
 }finally{globalThis.fetch=original;console.log=originalLog;console.error=originalError;}
});
function setup(){
 const values=new Map();let queue=Promise.resolve(),clock=1800000000000,alarm=null;const mail=[];
 const storage={get:async k=>structuredClone(values.get(k)),put:async(k,v)=>values.set(k,structuredClone(v)),delete:async k=>values.delete(k),list:async({prefix})=>new Map([...values].filter(([k])=>k.startsWith(prefix))),getAlarm:async()=>alarm,setAlarm:async t=>{alarm=t;},transaction(cb){const run=queue.then(()=>cb(storage));queue=run.catch(()=>{});return run;}};
 const env={ALLOWED_ORIGIN:'https://app.example',STRIPE_BILLING_MODE:'test',SUBSCRIBER_IDENTITY_SECRET:'synthetic-secret-'.repeat(4),SUBSCRIBER_APP_ORIGIN:'https://app.example',SUBSCRIBER_EMAIL_ENABLED:'true'};
 const limiter=new BetaUsageLimiter({storage},env);env.BETA_USAGE_LIMITER={idFromName:n=>n,get:()=>({fetch:(u,o)=>limiter.fetch(new Request(u,o))})};
 const handler=createHandler({now:()=>clock,subscriberEmailSender:async message=>{mail.push(message);return true;}});
 const call=(path,body={},headers={})=>handler(new Request('https://api.example/v1/subscriber/'+path,{method:'POST',headers:{Origin:'https://app.example','Content-Type':'application/json',...headers},body:JSON.stringify(body)}),env);
 const browserToken='a'.repeat(64);const start=()=>call('challenge',{email:'payer@example.com',browserToken});
 const token=()=>new URL(mail.at(-1).url).hash.slice('#subscriber_verify='.length);
 return {handler,values,storage,env,limiter,call,start,token,mail,browserToken,advance:ms=>{clock+=ms;}};
}
test('verified email creates distinct revocable bearer session, no email or bearer persisted',async()=>{const s=setup();const r=await s.start();assert.equal(r.status,202);assert.deepEqual(await r.json(),{accepted:true});assert.equal(s.mail.length,1);const link=new URL(s.mail[0].url);assert.equal(link.search,'');assert.equal(link.pathname,'/');assert.match(link.hash,/^#subscriber_verify=[a-f0-9]{64}$/);const token=s.token();assert.match(token,/^[a-f0-9]{64}$/);const verified=await s.call('verify',{token,browserToken:s.browserToken});assert.equal(verified.status,200);const session=await verified.json();assert.match(session.sessionToken,/^[a-f0-9]{64}$/);assert.notEqual(session.sessionToken,token);assert.equal(verified.headers.get('Cache-Control'),'no-store');const auth={Authorization:'Bearer '+session.sessionToken};const status=await s.call('session',{},auth);assert.equal(status.status,200);assert.match((await status.json()).principal,/^[a-f0-9]{64}$/);assert.equal((await s.call('logout',{},auth)).status,200);assert.equal((await s.call('session',{},auth)).status,401);const persisted=JSON.stringify([...s.values]);for(const secret of [token,session.sessionToken,s.browserToken,'payer@example.com'])assert.equal(persisted.includes(secret),false);});
test('wrong browser, replay and concurrent verification cannot mint sessions',async()=>{const s=setup();await s.start();const body={token:s.token(),browserToken:s.browserToken};assert.equal((await s.call('verify',{...body,browserToken:'b'.repeat(64)})).status,401);const results=await Promise.all(Array.from({length:12},()=>s.call('verify',body)));assert.equal(results.filter(r=>r.status===200).length,1);assert.equal((await s.call('verify',body)).status,401);});
test('challenge expires',async()=>{const s=setup();await s.start();s.advance(600000);assert.equal((await s.call('verify',{token:s.token(),browserToken:s.browserToken})).status,401);});
test('session expires without becoming anonymous or approving device',async()=>{const s=setup();await s.start();const r=await s.call('verify',{token:s.token(),browserToken:s.browserToken});assert.equal(r.status,200);const {sessionToken}=await r.json();s.advance(86400000);assert.equal((await s.call('session',{}, {Authorization:'Bearer '+sessionToken})).status,401);assert.equal([...s.values.keys()].some(k=>k.startsWith('invite:')||k.startsWith('paid-binding:')),false);});
test('challenge throttling is generic and bounded per email, network and globally',async()=>{const s=setup();for(let i=0;i<6;i++)assert.deepEqual(await (await s.start()).json(),{accepted:true});assert.equal(s.mail.length,3);});
test('disabled config, hostile origins, extra ownership fields and URL tokens fail closed',async()=>{const s=setup();assert.equal((await s.call('challenge',{email:'payer@example.com',browserToken:s.browserToken},{Origin:'https://evil.example'})).status,403);assert.equal((await s.call('challenge',{email:'payer@example.com',browserToken:s.browserToken,customerId:'cus_forged'})).status,400);assert.equal((await s.call('session?token=secret')).status,400);s.env.STRIPE_BILLING_MODE='live';assert.equal((await s.start()).status,503);});
test('cleanup removes expired auth records without touching billing',async()=>{const s=setup();s.values.set('subscriber:expired',{expiresAt:1});s.values.set('paid-binding:keep',{principal:'fixture'});await s.limiter.alarm();assert.equal(s.values.has('subscriber:expired'),false);assert.equal(s.values.has('paid-binding:keep'),true);});
